CREATE TABLE [dbo].[MATERIA]
(
[COD_MATERIA] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[NOMRE_MATERIA] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CANT_CREDITOS] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MATERIA] ADD CONSTRAINT [PK_MATERIA] PRIMARY KEY CLUSTERED  ([COD_MATERIA]) ON [PRIMARY]
GO
