CREATE TABLE [dbo].[SECCION]
(
[COD_SECCION] [int] NOT NULL,
[HORARIO] [xml] NOT NULL,
[COD_PROFESOR] [int] NOT NULL,
[COD_MATERIA] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECCION] ADD CONSTRAINT [PK_SECCION] PRIMARY KEY CLUSTERED  ([COD_SECCION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SECCION] ADD CONSTRAINT [FK_SECCION_MATERIA] FOREIGN KEY ([COD_MATERIA]) REFERENCES [dbo].[MATERIA] ([COD_MATERIA])
GO
ALTER TABLE [dbo].[SECCION] ADD CONSTRAINT [FK_SECCION_PROFESOR] FOREIGN KEY ([COD_PROFESOR]) REFERENCES [dbo].[PROFESOR] ([COD_PROFESOR])
GO
