CREATE TABLE [dbo].[PROFESOR]
(
[COD_PROFESOR] [int] NOT NULL,
[NOMBRE_PROF] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[APELLIDO_PROF] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[NUMERO] [varchar] (15) COLLATE Latin1_General_CI_AS NOT NULL,
[CORREO] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROFESOR] ADD CONSTRAINT [PK_PROFESOR] PRIMARY KEY CLUSTERED  ([COD_PROFESOR]) ON [PRIMARY]
GO
