CREATE TABLE [dbo].[CUATRIMESTRE]
(
[COD_CARRERA] [int] NOT NULL,
[COD_MATERIA] [varchar] (10) COLLATE Latin1_General_CI_AS NOT NULL,
[NUM_CUATRIMESTRE] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUATRIMESTRE] ADD CONSTRAINT [PK_CUATRIMESTRE] PRIMARY KEY CLUSTERED  ([COD_CARRERA], [COD_MATERIA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUATRIMESTRE] ADD CONSTRAINT [FK_CUATRIMESTRE_CARRERA] FOREIGN KEY ([COD_CARRERA]) REFERENCES [dbo].[CARRERA] ([COD_CARRERA])
GO
ALTER TABLE [dbo].[CUATRIMESTRE] ADD CONSTRAINT [FK_CUATRIMESTRE_MATERIA] FOREIGN KEY ([COD_MATERIA]) REFERENCES [dbo].[MATERIA] ([COD_MATERIA])
GO
