CREATE TABLE [dbo].[CARRERA]
(
[COD_CARRERA] [int] NOT NULL,
[NOMBRE] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL,
[CANT_CREDITOS] [int] NOT NULL,
[COD_DECANATO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARRERA] ADD CONSTRAINT [PK_CARRERA] PRIMARY KEY CLUSTERED  ([COD_CARRERA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARRERA] ADD CONSTRAINT [FK_CARRERA_DECANATO] FOREIGN KEY ([COD_DECANATO]) REFERENCES [dbo].[DECANATO] ([COD_DECANATO])
GO
