CREATE TABLE [dbo].[DECANATO]
(
[COD_DECANATO] [int] NOT NULL,
[NOMBRE] [varchar] (50) COLLATE Latin1_General_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DECANATO] ADD CONSTRAINT [PK_DECANATO] PRIMARY KEY CLUSTERED  ([COD_DECANATO]) ON [PRIMARY]
GO
