CREATE TABLE [dbo].[ESTUDIANTE_SECCION]
(
[MATRICULA] [int] NOT NULL,
[COD_SECCION] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTUDIANTE_SECCION] ADD CONSTRAINT [PK_ESTUDIANTE_SECCION] PRIMARY KEY CLUSTERED  ([MATRICULA], [COD_SECCION]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESTUDIANTE_SECCION] ADD CONSTRAINT [FK_ESTUDIANTE_SECCION_ESTUDIANTE] FOREIGN KEY ([MATRICULA]) REFERENCES [dbo].[ESTUDIANTE] ([MATRICULA])
GO
ALTER TABLE [dbo].[ESTUDIANTE_SECCION] ADD CONSTRAINT [FK_ESTUDIANTE_SECCION_SECCION] FOREIGN KEY ([COD_SECCION]) REFERENCES [dbo].[SECCION] ([COD_SECCION])
GO
